v0.0.5-172 : QuadRenderer::drawLine() implementation

diff --git a/rainbrurpg/configure b/rainbrurpg/configure
--- a/rainbrurpg/configure
+++ b/rainbrurpg/configure
@@ -905,6 +905,8 @@ RB_OPTION_ALL_FLAGS_TRUE
 RB_OPTION_ALL_FLAGS_FALSE
 RB_SCROLLPANE_TEST_TRUE
 RB_SCROLLPANE_TEST_FALSE
+RB_MULTICOLUMNLIST_TEST_TRUE
+RB_MULTICOLUMNLIST_TEST_FALSE
 ALLOCA
 LIBOBJS
 LTLIBOBJS'
@@ -1535,6 +1537,9 @@ Optional Features:
   --enable-scrollp-test   Build a scrollpane test window in the main menu game
                           state. It is only a developper option, used during
                           scrollpane implementation. (default=no)
+  --enable-mcl-test       Build a MultiColumnList test window in the main menu
+                          game state. It is only a developper option, used
+                          during MultiColumnList implementation. (default=no)
   --enable-debug          Build the package with local admin-site
                           authentification and informative logging
                           informations. Should be for developpers only.
@@ -5378,7 +5383,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 5381 "configure"' > conftest.$ac_ext
+  echo '#line 5386 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -7958,11 +7963,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7961: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7966: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7965: \$? = $ac_status" >&5
+   echo "$as_me:7970: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -8248,11 +8253,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:8251: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:8256: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:8255: \$? = $ac_status" >&5
+   echo "$as_me:8260: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -8352,11 +8357,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:8355: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:8360: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:8359: \$? = $ac_status" >&5
+   echo "$as_me:8364: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -10729,7 +10734,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 10732 "configure"
+#line 10737 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -10829,7 +10834,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 10832 "configure"
+#line 10837 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -13230,11 +13235,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13233: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13238: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:13237: \$? = $ac_status" >&5
+   echo "$as_me:13242: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -13334,11 +13339,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13337: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13342: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:13341: \$? = $ac_status" >&5
+   echo "$as_me:13346: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -14932,11 +14937,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14935: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14940: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:14939: \$? = $ac_status" >&5
+   echo "$as_me:14944: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -15036,11 +15041,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15039: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15044: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:15043: \$? = $ac_status" >&5
+   echo "$as_me:15048: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -17256,11 +17261,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17259: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17264: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:17263: \$? = $ac_status" >&5
+   echo "$as_me:17268: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -17546,11 +17551,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17549: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17554: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:17553: \$? = $ac_status" >&5
+   echo "$as_me:17558: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -17650,11 +17655,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17653: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17658: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:17657: \$? = $ac_status" >&5
+   echo "$as_me:17662: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -22536,16 +22541,16 @@ fi
 
   # Check whether --enable-scrollp-test was given.
 if test "${enable_scrollp_test+set}" = set; then
-  enableval=$enable_scrollp_test; build_server=$enableval
+  enableval=$enable_scrollp_test; scrollp_test=$enableval
 else
-  build_server=no
+  scrollp_test=no
 fi
 
 
   { echo "$as_me:$LINENO: checking if we should build scrollpane test window" >&5
 echo $ECHO_N "checking if we should build scrollpane test window... $ECHO_C" >&6; }
 
-  case $build_server in
+  case $scrollp_test in
     yes)
       scrollpane_test=true
 
@@ -22574,6 +22579,50 @@ if test x$scrollpane_test = xtrue; then
 else
   RB_SCROLLPANE_TEST_TRUE='#'
   RB_SCROLLPANE_TEST_FALSE=
+fi
+
+
+
+  # Check whether --enable-mcl-test was given.
+if test "${enable_mcl_test+set}" = set; then
+  enableval=$enable_mcl_test; mcl_test=$enableval
+else
+  mcl_test=no
+fi
+
+
+  { echo "$as_me:$LINENO: checking if we should build MultiColumnList test window" >&5
+echo $ECHO_N "checking if we should build MultiColumnList test window... $ECHO_C" >&6; }
+
+  case $mcl_test in
+    yes)
+      _mcl_test=true
+
+cat >>confdefs.h <<\_ACEOF
+#define RB_MULTICOLUMNLIST_TEST
+_ACEOF
+
+      cat >>confdefs.h <<\_ACEOF
+#define RB_MULTICOLUMNLIST_TEST 1
+_ACEOF
+
+      { echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+      ;;
+    *)
+      _mcl_test=false
+      { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+      ;;
+  esac
+
+
+if test x$_mcl_test = xtrue; then
+  RB_MULTICOLUMNLIST_TEST_TRUE=
+  RB_MULTICOLUMNLIST_TEST_FALSE='#'
+else
+  RB_MULTICOLUMNLIST_TEST_TRUE='#'
+  RB_MULTICOLUMNLIST_TEST_FALSE=
 fi
 
 
@@ -25890,6 +25939,13 @@ echo "$as_me: error: conditional \"RB_SCROLLPANE_TEST\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
+if test -z "${RB_MULTICOLUMNLIST_TEST_TRUE}" && test -z "${RB_MULTICOLUMNLIST_TEST_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"RB_MULTICOLUMNLIST_TEST\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"RB_MULTICOLUMNLIST_TEST\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
 
 : ${CONFIG_STATUS=./config.status}
 ac_clean_files_save=$ac_clean_files
@@ -26644,12 +26700,14 @@ RB_OPTION_ALL_FLAGS_TRUE!$RB_OPTION_ALL_FLAGS_TRUE$ac_delim
 RB_OPTION_ALL_FLAGS_FALSE!$RB_OPTION_ALL_FLAGS_FALSE$ac_delim
 RB_SCROLLPANE_TEST_TRUE!$RB_SCROLLPANE_TEST_TRUE$ac_delim
 RB_SCROLLPANE_TEST_FALSE!$RB_SCROLLPANE_TEST_FALSE$ac_delim
+RB_MULTICOLUMNLIST_TEST_TRUE!$RB_MULTICOLUMNLIST_TEST_TRUE$ac_delim
+RB_MULTICOLUMNLIST_TEST_FALSE!$RB_MULTICOLUMNLIST_TEST_FALSE$ac_delim
 ALLOCA!$ALLOCA$ac_delim
 LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 44; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 46; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
